# Grafana datasources configuration

apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    basicAuth: false
    jsonData:
      timeInterval: "15s"
      queryTimeout: "60s"
      httpMethod: GET
    secureJsonData: {}

  # PostgreSQL datasource (optional for direct database queries)
  - name: PostgreSQL
    type: postgres
    access: proxy
    url: postgres:5432
    database: amazon_insights
    user: postgres
    editable: true
    jsonData:
      sslmode: disable
      maxOpenConns: 10
      maxIdleConns: 2
      connMaxLifetime: 14400
    secureJsonData:
      password: postgres  # Change this in production